### PR TITLE
Google Maps Place

### LINKED ISSUE #193: Place Results

### PR DESCRIPTION
**Pull request by Mykhailo-Zub**
Resolves #193. [Draft](https://serpapi.com/blog/p/63d7e8dd-bc62-43fb-95a5-05882ac0784b/)

### CODE REVIEW

**Review by dimitryzub — CHANGES_REQUESTED** [review]
@Mykhailo-Zub Good job, thank you 💪

There are a few minor suggestions I've noticed. Other than that - 👍

**Review by dimitryzub — APPROVED** [review]
@Mykhailo-Zub LGTM, thank you 👍

**Comment by dimitryzub** [comment]
@Mykhailo-Zub let's set a reminder to publish this blog post.

@set-reminder Jul 25 5am @Mykhailo-Zub publish #247 blog post if you can and post so other blog platforms also.

**Comment by Mykhailo-Zub** [comment]
https://serpapi.com/blog/web-scraping-google-maps-place-with-nodejs/
https://medium.com/@mikhail.a.zub/web-scraping-google-maps-place-with-nodejs-8fe9486e4c71
https://tealfeed.com/web-scraping-google-maps-place-nodejs-t7p6s
https://dev.to/serpapi/web-scraping-google-maps-place-with-nodejs-26cb
https://serpapi.hashnode.dev/web-scraping-google-maps-place-with-nodejs

**Pull request merged**
